# Generated by Django 6.0.5 on 2026-05-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees',
            name='admission_fees',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fees',
            name='book_fees',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fees',
            name='dress_fees',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fees',
            name='exam_fees',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fees',
            name='insurance_fees',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fees',
            name='transport_fees',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fees',
            name='tuition_fees',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
