# Generated by Django 6.0.5 on 2026-05-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_fees_admission_fees_fees_book_fees_fees_dress_fees_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('period1', models.CharField(max_length=100)),
                ('period2', models.CharField(max_length=100)),
                ('period3', models.CharField(max_length=100)),
                ('period4', models.CharField(max_length=100)),
                ('period5', models.CharField(max_length=100)),
                ('period6', models.CharField(max_length=100)),
            ],
        ),
    ]
